### ISSUE TITLE
(CMOR) sftof in global_mean for ocean vars

### ISSUE THREAD

**Issue by jhardenberg** [oloapinivad/ECmean4#38]
In computing global means of ocean variables for CMOR data, we should actually use the information in sftof (the fraction of a cell covered by ocean). For NEMO this is always 100%, but not necessarily so for other models which might have fractional coverage.

**Comment by oloapinivad** [comment]
I had a look at this issue in `devel/refactor` in https://github.com/oloapinivad/ECmean4/pull/59/commits/ff5066104755144b9136b9e6375a1a76421ad615,  introducing an oceanic mask file that can be used if available. 

The idea is to use it for oceanic variable if available, but it is not a mandatory requirement to run. 

However, it is not possible to fully exploit this functionality since there is a bit of confusion between the "mask" (i.e. which are of the globe needs to be masked) and the "integration domain" (where to perform the integrals): the `reference` and `climatology` files use a similar key for very different goals. 

For the moment I am happy with the current solution, we might want to revisit in the future, maybe starting from the `yml` files.
